-- Placeholder for StratumBoiler component installation SQL
-- Example:
-- CREATE TABLE IF NOT EXISTS `#__stratumboiler_items` (
--  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
--  `title` VARCHAR(255) NOT NULL,
--  `published` TINYINT(1) NOT NULL DEFAULT 0,
--  PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
